### ISSUE TITLE
ProjectShareGroup fails to delete when already deleted

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi-gitlab#114]
We deleted a group in GitLab, so the ProjectShareGroup is removed from the gitlab.com platform. However, pulumi still tries to remove the group as a member of a project, and fails because the API returns an error (404). Running a refresh does not make pulumi aware that the group is no longer a member, and thus the only way to solve this appears to be modifying the state directly, which should never need to happen.

## Expected behavior
The group is seen as already having been removed as a member of the project.

## Current behavior
Pulumi still thinks the group is a member of the project.

## Steps to reproduce
1. Create a GitLab Project (directly or either via pulumi)
2. Create a GitLab Sub Group (directory or either via pulumi)
3. Share the project with the group (via pulumi)
4. Remove the group from the project (Directly on gitlab)
5. Run pulumi up

## Context (Environment)
We had to recreate a group that is shared in every one of our applications. While we don't have gitlab setup in pulumi (yet) for each application, there's still about 20 applications we will probably have to manually modify the state for.

**Comment by 1oglop1** [comment]
@stack72 I believe this is related gitlabhq/terraform-provider-gitlab/issues/1194 and going to be fixed by gitlabhq/terraform-provider-gitlab/pull/1209
