### ISSUE TITLE
group ids not being removed from a gitlab:index:ProjectApprovalRule

### ISSUE THREAD

**Issue by alexbowers** [pulumi/pulumi-gitlab#122]
When trying to update a Project Approval Rule to be user_ids not group_ids, the user gets set but the group doesn't get removed.

```
 ~   ├─ gitlab:index:ProjectApprovalRule  ProjectApprovalRule:Developers(23833179)  updated     [diff: -groupIds]
```

I get no errors, and it says `updated` however if I run an API call against Gitlab, I can see the group is still there, and I can run the `preview` and it will still try to remove them again.

---

Current workaround is to delete the approval rule and then re-create a new one, but this isn't ideal.

**Comment by lblackstone** [comment]
I'm guessing this may be an upstream bug.

**Comment by alexbowers** [comment]
How can I get an example of the api call you send to gitlab for the report or are you going to report it upstream?

Thanks


________________________________

**Comment by 1oglop1** [comment]
@stack72 Is this still relevant? it is pretty old. 
I tried to search the upstream but could not find anything specific.
@alexbowers if this is still an issue you can use TF_LOG=DEBUG https://www.pulumi.com/docs/support/troubleshooting/

**Comment by iwahbe** [comment]
Feel free to re-open this if you are still having trouble.
