### ISSUE TITLE
Can't create projects without a mirror url in 4.2.0 [python]

### ISSUE THREAD

**Issue by fitzoh** [pulumi/pulumi-gitlab#128]
I'm attempting to use the recently released 4.2.0 version of the provider in Python.
Pulumi is erroring out immediately if I don't set the `import_url` in a `Project`.

## Steps to reproduce
1. Create a gitlab project like this: `gitlab.Project("project")`

Expected: 
It should work and show me the expected change

Actual: 
I get an error like this:
```
    error: gitlab:index/project:Project resource 'project' has a problem: "only_mirror_protected_branches": all of `import_url,only_mirror_protected_branches` must be specified
    error: gitlab:index/project:Project resource 'project' has a problem: "mirror": all of `import_url,mirror` must be specified
    error: gitlab:index/project:Project resource 'project' has a problem: "mirror_overwrites_diverged_branches": all of `import_url,mirror_overwrites_diverged_branches` must be specified
    error: gitlab:index/project:Project resource 'project' has a problem: "mirror_trigger_builds": all of `import_url,mirror_trigger_builds` must be specified
```
    
   If I roll back to the previous version or put a blank string in as the `import_url` field I am able to get past the error.

**Comment by Kamaradeivanov** [comment]
Same issue for me, but with Typescript lib.
Force to rollback to version 4.1.0.

**Comment by eliebou** [comment]
Same issue but when i try to rollback in 4.1.0, i get : 
`
 Building wheel for pulumi-gitlab (setup.py) ... \
`
And i'm stuck.

**Comment by adrianord** [comment]
This is still an issue with 4.7.0, and really needs to be addressed. The provider is unusable past 4.1.0

**Comment by stack72** [comment]
Hi folks

I am sorry this is an issue - it seems the provider is hitting this bug - https://github.com/pulumi/pulumi-terraform-bridge/issues/540

I can start to have a look at this over the next week - I am not sure this is a fast fix I'm afraid but at least this gives me a definite scenario to look at. I can have a look and see if we can remove the `RequiredWith` semantics to unblock this scenario in a fork of the Terraform provider

Paul

**Comment by adrianord** [comment]
@stack72 It's very much appreciated :)

**Comment by adrianord** [comment]
@stack72 Here is a repo I just made and confirmed it runs into the issue described here https://github.com/adrianord/pulumi-gitlab-issue-128-example

**Comment by stack72** [comment]
Folks, I am going to cut v4.7.1 on a green default branch build
