### ISSUE TITLE
Please relase the updated provider

### ISSUE THREAD

**Issue by Fuuzetsu** [pulumi/pulumi-gitlab#179]
Back in July, the code was updated to latest version of the GitLab provider. Amongst other things, it has a new `runner` resource.

It seems this hasn't been properly released into the wild to be used. Would be nice.

**Comment by Fuuzetsu** [comment]
I tried something like `npm install 'https://gitpkg.now.sh/pulumi/pulumi-gitlab/sdk/nodejs?daa0ce0cb7ca979e6d2093b452d7887b6091b757'` but that didn't get me far...

**Comment by stack72** [comment]
Hi @Fuuzetsu 

I am sorry! I have just created the v4.8.0 release - it will be available in the next 30 mins

Paul

**Comment by Fuuzetsu** [comment]
@stack72 Thank you, I was able to update the package from `npm` now.

I'd like to just note that the package is still out of date on the pulumi package registry: https://www.pulumi.com/registry/packages/gitlab/

**Comment by stack72** [comment]
The docs update is on it's way to the registry right now - it takes a little time :)
