### ISSUE TITLE
How to delete/update GroupCluster?

### ISSUE THREAD

**Issue by mklueh** [pulumi/pulumi-gitlab#29]
I think the title says it all, how can you update / delete GroupCluster configs?

**Comment by stack72** [comment]
Hi @mklueh 

Thanks for opening an issue here - I am going to need a little bit more information here before I can help. Are you currently managing the cluster configs with Pulumi or you want to manage it for a cluster that already exists? What does your current Pulumi code look like?

Paul

**Comment by mklueh** [comment]
@stack72 thanks for the quick answer. I´ve now experienced that Pulumi does it under the hood already. I had an existing config that I wanted to get, modify, set but I´ve just deleted it now and let Pulumi create it´s own.

**Comment by stack72** [comment]
ok @mklueh that makes more sense - please do let me know if you have any more questions / issues

Paul
