### ISSUE TITLE
Update go.mod module path to v6

### ISSUE THREAD

**Issue by FollieHiyuki** [pulumi/pulumi-gitlab#294]
### What happened?

https://github.com/pulumi/pulumi-gitlab/blob/81b0fa1739624c935a5e268c3659e07682657a17/sdk/go.mod#L1

The SDK is still using `/v4` suffix, so I can't import the latest version (v6.0.0) in my Pulumi Go project.

### Expected Behavior

Please update the module path to `github.com/pulumi/pulumi-gitlab/sdk/v6`! Thanks!

### Steps to reproduce

* Create an empty Go project with go.mod file
* go get github.com/pulumi/pulumi-gitlab/sdk/v6

### Output of `pulumi about`

CLI          
Version      3.72.0
Go Version   go1.20.4
Go Compiler  gc

Host     
OS       alpine
Version  3.18.0
Arch     x86_64

**Comment by aq17** [comment]
@FollieHiyuki Thanks for catching this issue and apologies for the inconvenience.
@t0yv0 I've opened a quick PR to resolve the issue manually to unblock https://github.com/pulumi/pulumi-gitlab/pull/295
