### ISSUE TITLE
No automating support

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-gitlab#337]
> warning: SetAutonaming call is currently ignored for bridged resources built with the Plugin Framework. Supporting this feature is tracked in pulumi/pulumi-terraform-bridge#917.

These resources miss autonaming:
- Application
- ComplianceFramework

**Comment by t0yv0** [comment]
Is this a duplicate of https://github.com/pulumi/pulumi-gitlab/issues/334 ?

**Comment by mikhailshilkov** [comment]
Yes, apparently I missed it, sorry for the noise!
