### ISSUE TITLE
Creating new GitLab Project gives error

### ISSUE THREAD

**Issue by gregbacchus** [pulumi/pulumi-gitlab#99]
I am trying to create a GitLab project, but can't figure out how to not get the following error.

Code that I'm using:

```typescripe
new Project('test-proj', { name: 'Test', path: 'test-proj' });
```

gives error:

```
  gitlab:index:Project (test-proj):
    error: json: cannot unmarshal array into Go value of type gitlab.Project
```

I'm using 
* pulumi v2.15.6
* pulumi plugin install resource gitlab v3.4.0

**Comment by leezen** [comment]
I wasn't able to reproduce this with the following:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as gitlab from "@pulumi/gitlab";

const project = new gitlab.Project("project", {
    name: "test",
    path: "test-proj"
});

export const url = project.webUrl;
```

**package.json**
```json
File: package.json
{
    "name": "pulumi-gitlab-99",
    "devDependencies": {
        "@types/node": "^10.0.0"
    },
    "dependencies": {
        "@pulumi/gitlab": "^3.4.0",
        "@pulumi/pulumi": "^2.0.0"
    }
}
```

Using pulumi v2.15.6.

Any chance you could try blowing away your `node_modules` and try again?

**Comment by gregbacchus** [comment]
Thanks for the suggestion.

After deleting `node_modules` and re-installing, I still get the same issue.

I'm running it in docker.

Here is a gist with details to reproduce https://gist.github.com/gregbacchus/6b42ee1d6db494f2f4508a6dc63acd1c

Please check the readme there.

**Comment by leezen** [comment]
Apologies for coming back to this a bit later. Using some of the later versions, I'm not able to reproduce w/ the gist you provided. When running with `pulumi/pulumi:latest` container and the following package.json

```
{
    "name": "gitlab-99",
    "devDependencies": {
        "@types/node": "^10.0.0"
    },
    "dependencies": {
        "@pulumi/gitlab": "^3.6.0",
        "@pulumi/pulumi": "^2.0.0"
    }
}

```

I'm able to successfully create a project using the README steps.

Trying with with the v2.15.6 tagged container image, I also can't seem to reproduce this.

**Comment by gregbacchus** [comment]
Hey @leezen 

I have tried this again, and it's still failing. I have tried all combinations of the versions referenced above in this ticket and the latest versions of both `@pulumi/gitlab` (3.6.0 and 3.7.0) and the `pulumi` container (2.15.6 and 2.21.2).

A very similar issue occurs when I try to create Groups.

**Comment by leezen** [comment]
@gregbacchus Can you please provide additional repro details? As I mentioned, I wasn't able to reproduce. Do you mind sharing more details on how you're mapping your volumes, installing dependencies, etc.?

**Comment by gregbacchus** [comment]
@leezen 

I have made a github repo that reproduces the issue as precisely as I can in a docker container: https://github.com/gregbacchus/pulumi-gitlab-issue-99

Maybe worth noting the following:

- I'm running against an **on-prem** install of Gitlab which is running version `13.9.1-ee (8ae438629fa)` - which is the latest version at the time of writing
- I have reproduced this issue with `local` (this example) and s3 `cloud-url` backends

The output when I run the scripts in the repo for me are

```
root@54f2ae61768c:/src# ./up.sh 

> protobufjs@6.10.2 postinstall /app/node_modules/protobufjs
> node scripts/postinstall


> @pulumi/gitlab@v3.7.0 install /app/node_modules/@pulumi/gitlab
> node scripts/install-pulumi-plugin.js resource gitlab v3.7.0

[resource plugin gitlab-3.7.0] installing
Downloading plugin: 18.28 MiB / 18.28 MiB [=========================] 100.00% 2s
added 120 packages in 6.505s
Logged in to 54f2ae61768c as root (file://~)
[resource plugin gitlab-3.4.0] installing
Downloading plugin: 18.15 MiB / 18.15 MiB [=========================] 100.00% 2s
Created stack 'sandbox'
Previewing update (sandbox):

 +  pulumi:pulumi:Stack pulumi-gitlab-99-sandbox create 
 +  gitlab:index:Project project create 
 +  pulumi:pulumi:Stack pulumi-gitlab-99-sandbox create 
 
Resources:
    + 2 to create

Updating (sandbox):

 +  pulumi:pulumi:Stack pulumi-gitlab-99-sandbox creating 
 +  gitlab:index:Project project creating 
 +  gitlab:index:Project project creating error: json: cannot unmarshal array into Go value of type gitlab.Project
 +  gitlab:index:Project project **creating failed** error: json: cannot unmarshal array into Go value of type gitlab.Project
 +  pulumi:pulumi:Stack pulumi-gitlab-99-sandbox creating error: update failed
 +  pulumi:pulumi:Stack pulumi-gitlab-99-sandbox **creating failed** 1 error
 
Diagnostics:
  pulumi:pulumi:Stack (pulumi-gitlab-99-sandbox):
    error: update failed
 
  gitlab:index:Project (project):
    error: json: cannot unmarshal array into Go value of type gitlab.Project
 
Resources:
    + 1 created

Duration: 5s
```

**Comment by leezen** [comment]
I cloned your repo and ran the scripts, but was successfully able to create the project. However, I don't have an on-prem installation of GitLab and have been testing against the hosted offering. I think what could be helpful at this point from a debugging perspective is to run with `-v=9 --logtostderr 2>log.out` and seeing if the log includes information about what the underlying value it's trying to unmarshal is and what the discrepancy might be.

**Comment by gregbacchus** [comment]
Do you know how stupid I feel?! I just figured out that my problem was that accidentally I set `GITLAB_BASE_URL` to `http://...` instead of `https://...`.

@leezen Thanks for you help and sorry for wasting your time.

**Comment by leezen** [comment]
@gregbacchus Don't feel bad. I'm glad you got it sorted out!

**Comment by gregbacchus** [comment]
The error was (now clearly) an issue parsing the response from the server. Maybe this is an opportunity to display the output if it can't be parsed? Also if it's not a 20X response, maybe a specific message would be helpful :)
